// components/DataForm/field-configs.ts
import { ExportDocumentType } from "./ExportPopup";
import { TFunction } from "i18next";

export interface FieldConfig {
  display: string;
  technical: string;
}

export interface DocumentFieldsConfig {
  fields: FieldConfig[];
  displayName: string;
}

// export const receiptFields: FieldConfig[] = [
//   { display: 'Receipt Number', technical: 'receipt_number' },
//   { display: 'Transaction Datetime', technical: 'transaction_datetime' },
//   { display: 'Barcode Data', technical: 'barcode_data' },
//   { display: 'Cashier ID', technical: 'cashier_id' },
//   { display: 'Change Amount', technical: 'change_amount' },
//   { display: 'Currency', technical: 'currency' },
//   { display: 'Customer GST Number', technical: 'customer.GST_number' },
//   { display: 'Customer QST Number', technical: 'customer.QST_number' },
//   { display: 'Customer City', technical: 'customer.address.city' },
//   { display: 'Customer Country', technical: 'customer.address.country' },
//   { display: 'Customer Postal Code', technical: 'customer.address.postal_code' },
//   { display: 'Customer State', technical: 'customer.address.state' },
//   { display: 'Customer Street', technical: 'customer.address.street' },
//   { display: 'Customer Email', technical: 'customer.email' },
//   { display: 'Customer Fax', technical: 'customer.fax' },
//   { display: 'Customer Name', technical: 'customer.name' },
//   { display: 'Customer Other Contact Info', technical: 'customer.other_contact_info' },
//   { display: 'Customer Phone', technical: 'customer.phone' },
//   { display: 'Customer VAT Number', technical: 'customer.vat_number' },
//   { display: 'Customer Website', technical: 'customer.website' },
//   { display: 'Discount Lines', technical: 'discount_lines' },
//   { display: 'Is Receipt', technical: 'is_receipt' },
//   { display: 'Lines Amount', technical: 'lines.amount' },
//   { display: 'Lines Description', technical: 'lines.description' },
//   { display: 'Lines Quantity', technical: 'lines.quantity' },
//   { display: 'Lines Unit Price', technical: 'lines.unit_price' },
//   { display: 'Loyalty Info', technical: 'loyalty_info' },
//   { display: 'Merchant GST Number', technical: 'merchant.GST_number' },
//   { display: 'Merchant QST Number', technical: 'merchant.QST_number' },
//   { display: 'Merchant City', technical: 'merchant.address.city' },
//   { display: 'Merchant Country', technical: 'merchant.address.country' },
//   { display: 'Merchant Postal Code', technical: 'merchant.address.postal_code' },
//   { display: 'Merchant State', technical: 'merchant.address.state' },
//   { display: 'Merchant Street', technical: 'merchant.address.street' },
//   { display: 'Merchant Email', technical: 'merchant.email' },
//   { display: 'Merchant Fax', technical: 'merchant.fax' },
//   { display: 'Merchant Name', technical: 'merchant.name' },
//   { display: 'Merchant Other Contact Info', technical: 'merchant.other_contact_info' },
//   { display: 'Merchant Phone', technical: 'merchant.phone' },
//   { display: 'Merchant Registration Number', technical: 'merchant.registration_number' },
//   { display: 'Merchant VAT Number', technical: 'merchant.vat_number' },
//   { display: 'Merchant Website', technical: 'merchant.website' },
//   { display: 'Payment Method Account Name', technical: 'payment_method.account_name' },
//   { display: 'Payment Method Account Number', technical: 'payment_method.account_number' },
//   { display: 'Payment Method IBAN', technical: 'payment_method.iban' },
//   { display: 'Payment Method Name', technical: 'payment_method.method_name' },
//   { display: 'Payment Method Swift Code', technical: 'payment_method.swift_code' },
//   { display: 'Payment Methods', technical: 'payment_methods' },
//   { display: 'Promotion Codes', technical: 'promotion_codes' },
//   { display: 'Return Policy', technical: 'return_policy' },
//   { display: 'Shipping Amount', technical: 'shipping_amount' },
//   { display: 'Shipping Metod', technical: 'shipping_metod' },
//   { display: 'Store Number', technical: 'store_number' },
//   { display: 'Sub Total Amount', technical: 'sub_total_amount' },
//   { display: 'Subtotal', technical: 'subtotal' },
//   { display: 'Tax', technical: 'tax' },
//   { display: 'Tax 54545', technical: 'tax_54545' },
//   { display: 'Tax 778787', technical: 'tax_778787' },
//   { display: 'Tax GST + QST', technical: 'tax_GST_+_QST' },
//   { display: 'Tax TAX (GST 5 + QST 9.975)', technical: 'tax_TAX_(GST_5_+_QST_9.975)' },
//   { display: 'Tax Lines', technical: 'tax_lines' },
//   { display: 'Tendered Amount', technical: 'tendered_amount' },
//   { display: 'Tip', technical: 'tip' },
//   { display: 'Tip Lines', technical: 'tip_lines' },
//   { display: 'Total Amount', technical: 'total_amount' },
//   { display: 'Total Before Tip', technical: 'total_before_tip' },
// ];

// export const invoiceFields: FieldConfig[] = [
//     { display: 'Invoice Number', technical: 'invoice_number' },
//     { display: 'Invoice Date', technical: 'invoice_date' },
//     { display: 'Currency', technical: 'currency' },
//     { display: 'Customer', technical: 'customer' },
//     { display: 'Customer GST Number', technical: 'customer.GST_number' },
//     { display: 'Customer QST Number', technical: 'customer.QST_number' },
//     { display: 'Customer City', technical: 'customer.address.city' },
//     { display: 'Customer Country', technical: 'customer.address.country' },
//     { display: 'Customer Postal Code', technical: 'customer.address.postal_code' },
//     { display: 'Customer State', technical: 'customer.address.state' },
//     { display: 'Customer Street', technical: 'customer.address.street' },
//     { display: 'Customer Email', technical: 'customer.email' },
//     { display: 'Customer Fax', technical: 'customer.fax' },
//     { display: 'Customer Name', technical: 'customer.name' },
//     { display: 'Customer Other Contact Info', technical: 'customer.other_contact_info' },
//     { display: 'Customer Phone', technical: 'customer.phone' },
//     { display: 'Customer VAT Number', technical: 'customer.vat_number' },
//     { display: 'Customer Website', technical: 'customer.website' },
//     { display: 'Delivery City', technical: 'delivery_details.delivery_address.city' },
//     { display: 'Delivery Country', technical: 'delivery_details.delivery_address.country' },
//     { display: 'Delivery Postal Code', technical: 'delivery_details.delivery_address.postal_code' },
//     { display: 'Delivery State', technical: 'delivery_details.delivery_address.state' },
//     { display: 'Delivery Street', technical: 'delivery_details.delivery_address.street' },
//     { display: 'Delivery Date', technical: 'delivery_details.delivery_date' },
//     { display: 'Delivery Tracking Number', technical: 'delivery_details.tracking_number' },
//     { display: 'Discount Lines', technical: 'discount_lines' },
//     { display: 'Invoice Due Date', technical: 'invoice_due_date' },
//     { display: 'Is Invoice', technical: 'is_invoice' },
//     { display: 'Issue Datetime', technical: 'issue_datetime' },
//     { display: 'Lines Amount', technical: 'lines.amount' },
//     { display: 'Lines Description', technical: 'lines.description' },
//     { display: 'Lines Quantity', technical: 'lines.quantity' },
//     { display: 'Lines Unit Price', technical: 'lines.unit_price' },
//     { display: 'Notes', technical: 'notes' },
//     { display: 'Order Number', technical: 'order_number' },
//     { display: 'Payment Method Account Name', technical: 'payment_method.account_name' },
//     { display: 'Payment Method Account Number', technical: 'payment_method.account_number' },
//     { display: 'Payment Method IBAN', technical: 'payment_method.iban' },
//     { display: 'Payment Method Name', technical: 'payment_method.method_name' },
//     { display: 'Payment Method Swift Code', technical: 'payment_method.swift_code' },
//     { display: 'Promotion Codes', technical: 'promotion_codes' },
//     { display: 'Seller GST Number', technical: 'seller.GST_number' },
//     { display: 'Seller QST Number', technical: 'seller.QST_number' },
//     { display: 'Seller City', technical: 'seller.address.city' },
//     { display: 'Seller Country', technical: 'seller.address.country' },
//     { display: 'Seller Postal Code', technical: 'seller.address.postal_code' },
//     { display: 'Seller State', technical: 'seller.address.state' },
//     { display: 'Seller Street', technical: 'seller.address.street' },
//     { display: 'Seller Email', technical: 'seller.email' },
//     { display: 'Seller Fax', technical: 'seller.fax' },
//     { display: 'Seller Name', technical: 'seller.name' },
//     { display: 'Seller Other Contact Info', technical: 'seller.other_contact_info' },
//     { display: 'Seller Phone', technical: 'seller.phone' },
//     { display: 'Seller Registration Number', technical: 'seller.registration_number' },
//     { display: 'Seller VAT Number', technical: 'seller.vat_number' },
//     { display: 'Seller Website', technical: 'seller.website' },
//     { display: 'Sub Total Amount', technical: 'sub_total_amount' },
//     { display: 'Tax', technical: 'tax' },
//     { display: 'Tax GST+QST', technical: 'tax_GST+QST' },
//     { display: 'Tax TAXE', technical: 'tax_TAXE' },
//     { display: 'Tax Lines', technical: 'tax_lines' },
//     { display: 'Total Amount', technical: 'total_amount' },
// ];

export const getReceiptFields = (): FieldConfig[] => [
  { display: "receiptFields.receipt_number", technical: "receipt_number" },
  {
    display: "receiptFields.transaction_datetime",
    technical: "transaction_datetime",
  },
  { display: "receiptFields.barcode_data", technical: "barcode_data" },
  { display: "receiptFields.cashier_id", technical: "cashier_id" },
  { display: "receiptFields.change_amount", technical: "change_amount" },
  { display: "receiptFields.currency", technical: "currency" },
  {
    display: "receiptFields.customer.GST_number",
    technical: "customer.GST_number",
  },
  {
    display: "receiptFields.customer.QST_number",
    technical: "customer.QST_number",
  },
  {
    display: "receiptFields.customer.address.city",
    technical: "customer.address.city",
  },
  {
    display: "receiptFields.customer.address.country",
    technical: "customer.address.country",
  },
  {
    display: "receiptFields.customer.address.postal_code",
    technical: "customer.address.postal_code",
  },
  {
    display: "receiptFields.customer.address.state",
    technical: "customer.address.state",
  },
  {
    display: "receiptFields.customer.address.street",
    technical: "customer.address.street",
  },
  { display: "receiptFields.customer.email", technical: "customer.email" },
  { display: "receiptFields.customer.fax", technical: "customer.fax" },
  { display: "receiptFields.customer.name", technical: "customer.name" },
  {
    display: "receiptFields.customer.other_contact_info",
    technical: "customer.other_contact_info",
  },
  { display: "receiptFields.customer.phone", technical: "customer.phone" },
  {
    display: "receiptFields.customer.vat_number",
    technical: "customer.vat_number",
  },
  {
    display: "receiptFields.customer.website",
    technical: "customer.website",
  },
  { display: "receiptFields.discount_lines", technical: "discount_lines" },
  { display: "receiptFields.is_receipt", technical: "is_receipt" },
  { display: "receiptFields.lines.amount", technical: "lines.amount" },
  {
    display: "receiptFields.lines.description",
    technical: "lines.description",
  },
  { display: "receiptFields.lines.quantity", technical: "lines.quantity" },
  {
    display: "receiptFields.lines.unit_price",
    technical: "lines.unit_price",
  },
  { display: "receiptFields.loyalty_info", technical: "loyalty_info" },
  {
    display: "receiptFields.merchant.GST_number",
    technical: "merchant.GST_number",
  },
  {
    display: "receiptFields.merchant.QST_number",
    technical: "merchant.QST_number",
  },
  {
    display: "receiptFields.merchant.address.city",
    technical: "merchant.address.city",
  },
  {
    display: "receiptFields.merchant.address.country",
    technical: "merchant.address.country",
  },
  {
    display: "receiptFields.merchant.address.postal_code",
    technical: "merchant.address.postal_code",
  },
  {
    display: "receiptFields.merchant.address.state",
    technical: "merchant.address.state",
  },
  {
    display: "receiptFields.merchant.address.street",
    technical: "merchant.address.street",
  },
  { display: "receiptFields.merchant.email", technical: "merchant.email" },
  { display: "receiptFields.merchant.fax", technical: "merchant.fax" },
  { display: "receiptFields.merchant.name", technical: "merchant.name" },
  {
    display: "receiptFields.merchant.other_contact_info",
    technical: "merchant.other_contact_info",
  },
  { display: "receiptFields.merchant.phone", technical: "merchant.phone" },
  {
    display: "receiptFields.merchant.registration_number",
    technical: "merchant.registration_number",
  },
  {
    display: "receiptFields.merchant.vat_number",
    technical: "merchant.vat_number",
  },
  {
    display: "receiptFields.merchant.website",
    technical: "merchant.website",
  },
  {
    display: "receiptFields.payment_method.account_name",
    technical: "payment_method.account_name",
  },
  {
    display: "receiptFields.payment_method.account_number",
    technical: "payment_method.account_number",
  },
  {
    display: "receiptFields.payment_method.iban",
    technical: "payment_method.iban",
  },
  {
    display: "receiptFields.payment_method.method_name",
    technical: "payment_method.method_name",
  },
  {
    display: "receiptFields.payment_method.swift_code",
    technical: "payment_method.swift_code",
  },
  { display: "receiptFields.payment_methods", technical: "payment_methods" },
  { display: "receiptFields.promotion_codes", technical: "promotion_codes" },
  { display: "receiptFields.return_policy", technical: "return_policy" },
  { display: "receiptFields.shipping_amount", technical: "shipping_amount" },
  { display: "receiptFields.shipping_metod", technical: "shipping_metod" },
  { display: "receiptFields.store_number", technical: "store_number" },
  {
    display: "receiptFields.sub_total_amount",
    technical: "sub_total_amount",
  },
  { display: "receiptFields.subtotal", technical: "subtotal" },
  { display: "receiptFields.tax", technical: "tax" },
  { display: "receiptFields.tax_54545", technical: "tax_54545" },
  { display: "receiptFields.tax_778787", technical: "tax_778787" },
  { display: "receiptFields.tax_GST_+_QST", technical: "tax_GST_+_QST" },
  {
    display: "receiptFields.tax_TAX_(GST_5_+_QST_9.975)",
    technical: "tax_TAX_(GST_5_+_QST_9.975)",
  },
  { display: "receiptFields.tax_lines", technical: "tax_lines" },
  { display: "receiptFields.tendered_amount", technical: "tendered_amount" },
  { display: "receiptFields.tip", technical: "tip" },
  { display: "receiptFields.tip_lines", technical: "tip_lines" },
  { display: "receiptFields.total_amount", technical: "total_amount" },
  {
    display: "receiptFields.total_before_tip",
    technical: "total_before_tip",
  },
];

export const getInvoiceFields = (): FieldConfig[] => [
  { display: "invoiceFields.invoice_number", technical: "invoice_number" },
  { display: "invoiceFields.invoice_date", technical: "invoice_date" },
  { display: "invoiceFields.currency", technical: "currency" },
  { display: "invoiceFields.customer", technical: "customer" },
  {
    display: "invoiceFields.customer.GST_number",
    technical: "customer.GST_number",
  },
  {
    display: "invoiceFields.customer.QST_number",
    technical: "customer.QST_number",
  },
  {
    display: "invoiceFields.customer.address.city",
    technical: "customer.address.city",
  },
  {
    display: "invoiceFields.customer.address.country",
    technical: "customer.address.country",
  },
  {
    display: "invoiceFields.customer.address.postal_code",
    technical: "customer.address.postal_code",
  },
  {
    display: "invoiceFields.customer.address.state",
    technical: "customer.address.state",
  },
  {
    display: "invoiceFields.customer.address.street",
    technical: "customer.address.street",
  },
  { display: "invoiceFields.customer.email", technical: "customer.email" },
  { display: "invoiceFields.customer.fax", technical: "customer.fax" },
  { display: "invoiceFields.customer.name", technical: "customer.name" },
  {
    display: "invoiceFields.customer.other_contact_info",
    technical: "customer.other_contact_info",
  },
  { display: "invoiceFields.customer.phone", technical: "customer.phone" },
  {
    display: "invoiceFields.customer.vat_number",
    technical: "customer.vat_number",
  },
  {
    display: "invoiceFields.customer.website",
    technical: "customer.website",
  },
  { display: "invoiceFields.total_amount", technical: "total_amount" },
];
